name: SimpleWarp
main: simplewarp\SimpleWarp
version: 1.4
author: Falk
api: [1.0.0]
load: POSTWORLD
commands:
 warp:
  description: Warp to a location
  usage: /warp <название> [игрок]
 listwarps:
  description: List existing warps
  usage: /listwarps
 addwarp:
  permission: simplewarp.manage
  description: Add a new warp point
  usage: /addwarp <NAME>
 delwarp:
  permission: simplewarp.manage
  description: Delete a warp point
  usage: ¶Удалить варп¶ /delwarp <название>
permissions:
 simplewarp:
  default: op
  description: Top level SimpleWarp permission
  children:
   simplewarp.manage:
    default: op
    description: Manage all warps
   simplewarp.list:
    default: true
    description: Can view a list off accessible warps
   simplewarp.other:
    default: op
    description: Warp other players
   simplewarp.warp:
    default: op
    description: Allows usage of all warps
